package commonConst

var Code = commonConstType{
	RECORD_NOTFOUND:       "RECORD_NOTFOUND",
	DUPLICATE_RECORD:      "DUPLICATE_RECORD",
	UNAUTHORIZED:          "UNAUTHORIZED",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	TOO_MANY_REQUEST:      "TOO_MANY_REQUEST",
}
