package authConst

var Code = authConstType{
	INVALID_CREDENTIALS:       "INVALID_CREDENTIALS",
	UNAUTHORIZED:              "UNAUTHORIZED",
	NOT_FOUND_BEARER:          "NOT_FOUND_BEARER",
	BROKEN_TOKEN:              "BROKEN_TOKEN",
	MAX_DEVICES_LOGIN:         "MAX_DEVICES_LOGIN",
	INVALID_TOKEN:             "INVALID_TOKEN",
	TOKEN_EXPIRED:             "TOKEN_EXPIRED",
	NO_AUTHORIZATION_HEADER:   "NO_AUTHORIZATION_HEADER",
	NO_X_REFRESH_TOKEN_HEADER: "NO_X_REFRESH_TOKEN_HEADER",
}
